CREATE DATABASE cinematube;
USE cinematube;

CREATE TABLE usuarios(USUARIO_TYPE INT(1),USUARIO_CORREO VARCHAR(30),USUARIO_NOMBRE VARCHAR(20),USUARIO_PATERNO VARCHAR(15),USUARIO_MATERNO VARCHAR(15),USUARIO_CONTRASENIA VARCHAR(25),FECHA_REGISTRO DATE, PRIMARY KEY (USUARIO_CORREO));
